# Failable
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'Example' do
  pod 'Failable', :inhibit_warnings => false, :path => '..'

  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '3.3.0'
  pod 'ObjectMapper', '~> 3.0'
end

target 'Tests' do
  pod 'Failable', :inhibit_warnings => false, :path => '..'
end
