platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

target 'FailableExample' do
  pod 'Failable', :path => '..'
  pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift2.3'
  pod 'AlamofireImage', :git => 'git@github.com:Alamofire/AlamofireImage.git', :branch => 'swift2.3'
  pod 'ObjectMapper'
end

target 'FailableTests' do
  pod 'Failable', :path => '..'
end
