platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

target 'FailableExample' do
  pod 'Failable', :path => '..'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '3.3.0'
  pod 'ObjectMapper', '~> 2.0'
end

target 'FailableTests' do
  pod 'Failable', :path => '..'
end
