platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:WPMedia/Podspecs.git'

# inhibit_all_warnings!
use_frameworks!

target 'FailableExample' do
  pod 'Failable', :path => '..'
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireImage', '~> 2.0'
end

target 'FailableTests' do
  pod 'Failable', :path => '..'
end